---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: detail
  namespace: flagger
  labels:
    app: detail
spec:
  minReadySeconds: 5
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: detail
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9797"
        timestamp: "2021-03-28T14:24:48+0000"
      labels:
        app: detail
    spec:
      containers:
        - name: detail
          image: "public.ecr.aws/u2g6w7p2/eks-microservice-demo/detail:${APP_VERSION_3}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
            - name: http-metrics
              containerPort: 9797
              protocol: TCP
          # - name: grpc
          #   containerPort: 9999
          #   protocol: TCP
          # command:
          # - ./podinfo
          # - --port=9898
          # - --port-metrics=9797
          # - --grpc-port=9999
          # - --grpc-service-name=podinfo
          # - --level=info
          # - --random-delay=false
          # - --random-error=false
          # env:
          # - name: PODINFO_UI_COLOR
          #   value: "#34577c"
          livenessProbe:
            httpGet:
              path: /ping
              port: 3000
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ping
              port: 3000
            successThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
---