---
apiVersion: v1
kind: Namespace
metadata:
  name: flagger
  labels:
    mesh: flagger
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: Mesh
metadata:
  name: flagger
spec:
  namespaceSelector:
    matchLabels:
      mesh: flagger
---