# Default values for helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

detail:
  replicaCount: 1
  namespace: detail
  name: proddetail

  image:
    repository: 866572682550.dkr.ecr.us-east-1.amazonaws.com/spinnaker-test
    tag: "v2.0.1"
    pullPolicy: Always

  nameOverride: ""
  fullnameOverride: ""

  service:
    type: ClusterIP
    targetPort: 3000

  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    hosts:
      - host: proddetail.local
        paths: []

    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
  #   memory: 128Mi

  nodeSelector: 
    role: spinnaker

  tolerations: []

  affinity: {}

frontend:
  replicaCount: 1
  namespace: detail
  name: frontend
  lbType: alb

  image:
    repository: 866572682550.dkr.ecr.us-east-1.amazonaws.com/spinnaker-test
    tag: "v2.0.1"
    pullPolicy: Always

  nameOverride: ""
  fullnameOverride: ""

  service:
    type: LoadBalancer
    targetPort: 9000
    port: 9000
    name: "http"

  selector:
    app: frontend

  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: frontend.local
        paths: []

    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  env:
    - name: BASE_URL
      value: "http://proddetail.detail:3000/catalogDetail"
    
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  nodeSelector: 
    role: spinnaker

  tolerations: []

  affinity: {}
